### ISSUE TITLE
opene57 header still requires Boost

### ISSUE THREAD

**Issue by VisionaryMind** [madduci/openE57#8]
I was hoping this library would allow complete independence from Boost, since it cannot be used in our target environment (iOS 14 beta). Unfortunately, the opene57 header file still points to the boost libraries. Your description states replacing shared_ptr.hpp, for example, with "memory", but nonetheless, at the top of your opene57.h, you have shared_ptr, weak_ptr, cstdint, and a mysterious "enable_shared_from_this". 

How can this library be used without Boost? If this is an incomplete work in progress, you must state so in the main ReadMe file. Otherwise, we waste time trying to implement something that hasn't yet been fully developed. Clearly, this is not an open framework and still exclusively relies on Boost.

**Comment by madduci** [comment]
Hi

This work is still in progress, since the amount of Boost utilities used in the original source code is pretty huge and you can't simply replace everything in one shot, especially without testing.

**Comment by madduci** [comment]
I've removed almost all the Boost libraries/headers required by the core library, unfortunately Boost is still required, since it implements the CRC32-C and no valid alternative has been yet found  ( see #10 )

**Comment by madduci** [comment]
The core library doesn't require Boost anymore, it will be required only for tools and examples
